### ISSUE TITLE
Does not respect blank lines

### ISSUE THREAD

**Issue by mbdraks** [davidmogar/gitbook-plugin-terminal#1]
Hi,

This code:

```
**[terminal]
**[prompt FG]**[delimiter # ]**[command exec restore image management-station 05004000FIMG0012004004]
Please wait...

Getting image 05004000FIMG0012004004 from Management station...
#################################################################
This operation will replace the current firmware version!
Do you want to continue? (y/n)y


Checking new firmware integrity ... pass

Please wait for system to restart.
```

Will not respect the blank lines and simply remove them from output. Is there any way to prevent that ?

**Comment by davidmogar** [comment]
Hi @barbosm,

In my use case while developing the plugin a had not even a single blank line so I'm pretty sure I messed up . I will check this week and try to fix it.

Thank you for opening this issue ;)

**Comment by davidmogar** [comment]
Hi @barbosm,

I've released a new version with the fix. Hope now is better. Let me know if not ;)

Cheers,
David

**Comment by mbdraks** [comment]
Tks! I guess I'll have to wait for gitbook to update on their side. I'll let you know.
